DataProducts = [
  {
    img: "../IMAGE/office/1.jpg",
    title: "Ghế sofa gỗ cao su tự nnhiên Frederica 601",
    price: "7.990.000₫",
    ogPrice: "11.990.000₫",
    sale: "-34%",
    modalId: "productModal-1",
  },
  {
    img: "../IMAGE/office/2.jpg",
    title: "Ghế sofa gỗ cao su tự nnhiên Tromso 601",
    price: "11.990.000₫",
    ogPrice: "16.990.000₫",
    sale: "-30%",
    modalId: "productModal-2",
  },
  {
    img: "../IMAGE/office/3.jpg",
    title: "Ghế sofa gỗ cao su tự nnhiên Hobro 601",
    price: "14.990.000₫",
    ogPrice: "16.990.000₫",
    sale: "-12%",
    modalId: "productModal-3",
  },
  {
    img: "../IMAGE/office/4.jpg",
    title: "Bàn trà gỗ tự nhiên 5CBT-136",
    price: "6.590.000₫",
    ogPrice: "7.890.000₫",
    sale: "-17%",
    modalId: "productModal-4",
  },
  {
    img: "../IMAGE/office/5.jpg",
    title: "Bàn trà gỗ công nghiệp chân cao gỗ tự nhiên 5CBT-124",
    price: "4.589.000₫",
    ogPrice: "5.120.000₫",
    sale: "-11%",
    modalId: "productModal-5",
  },
  {
    img: "../IMAGE/office/6.jpg",
    title: "Bàn trang điểm module",
    price: "4.850.000₫",
    ogPrice: "5.960.000₫",
    sale: "-18%",
    modalId: "productModal-6",
  },
  {
    img: "../IMAGE/office/7.jpg",
    title: "Bàn trang điểm chân cao",
    price: "Liên hệ",
    ogPrice: "",
    sale: "",
    modalId: "productModal-7",
  },
  {
    img: "../IMAGE/office/8.jpg",
    title: "Bàn trà gỗ tự nhiên ngăn kéo sơn màu 5CBT-130",
    price: "Liên hệ",
    ogPrice: "",
    sale: "",
    modalId: "productModal-8",
  },
  {
    img: "../IMAGE/office/9.jpg",
    title: "Bàn trà phòng khách hiện đại 5CBT-17",
    price: "4.600.000₫",
    ogPrice: "",
    sale: "",
    modalId: "productModal-9",
  },
];
